#!/bin/bash

IDIR="${BASH_SOURCE%/*}"
if [[ ! -d "$IDIR" ]]; then IDIR="$PWD"; fi
source "$IDIR/inc/misc_tools.sh"

# Edit the following locations to provide the
TMUX=`which tmux`
if [ -z $TMUX ]; then
    TMUX=/usr/local/bin/tmux
fi

# No need to edit below this line unless you find a bug!

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF

jamterm tmux-id [terminal-num]
Shows the background terminals of with the given tmux-id and terminal-num.

For example, to see the second terminal of a program running with u-600-dev-2331
type jamterm u-600-dev-2331-2. Note that terminal-num is optional.

EOF
}

localtmux() {
    local tmuxapp=$1
    local termno=$2

    $TMUX has-session -t $tmuxapp 2>/dev/null
    res=$?
    if [ $res == "0" ]; then
        if [ -z $termno ]; then
            $TMUX attach -t $tmuxapp
        else
            $TMUX attach -t $tmuxapp-$termno
        fi
    fi
}


###
# Main script execution begins here...
#

if [ -z $1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    show_usage
    exit
fi


localtmux $1 $2
